"""Formatter utilities for digest generation."""

from datetime import datetime

from discord_chat.services.discord_client import ServerDigestData


def format_messages_for_llm(data: ServerDigestData) -> str:
    """Format Discord messages into text for LLM consumption.

    Args:
        data: Server digest data containing all messages.

    Returns:
        Formatted text string with messages organized by channel.
    """
    if not data.channels:
        return "No messages found in the specified time period."

    lines = []
    for channel in data.channels:
        lines.append(f"## #{channel.channel_name}")
        lines.append("")

        for msg in channel.messages:
            timestamp = msg["timestamp"][:16].replace("T", " ")  # Trim to minute precision
            author = msg["author"]
            content = msg["content"]

            # Format the message
            lines.append(f"[{timestamp}] **{author}**: {content}")

            # Note attachments if any
            if msg["attachments"]:
                attachments = ", ".join(msg["attachments"])
                lines.append(f"  _Attachments: {attachments}_")

        lines.append("")

    return "\n".join(lines)


def format_time_range(start: datetime, end: datetime) -> str:
    """Format the time range for display.

    Args:
        start: Start datetime.
        end: End datetime.

    Returns:
        Human-readable time range string.
    """
    start_str = start.strftime("%Y-%m-%d %H:%M UTC")
    end_str = end.strftime("%Y-%m-%d %H:%M UTC")
    return f"{start_str} to {end_str}"


def create_digest_header(data: ServerDigestData, llm_name: str) -> str:
    """Create the header section for the digest output.

    Args:
        data: Server digest data.
        llm_name: Name of the LLM used for generation.

    Returns:
        Markdown header string.
    """
    time_range = format_time_range(data.start_time, data.end_time)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""# Discord Digest: {data.server_name}

**Generated:** {generated_at}
**Time Period:** {time_range}
**Channels with activity:** {len(data.channels)}
**Total messages:** {data.total_messages}
**Generated by:** {llm_name}

---

"""


def create_full_digest(
    data: ServerDigestData,
    llm_digest: str,
    llm_name: str,
) -> str:
    """Create the full digest document.

    Args:
        data: Server digest data.
        llm_digest: The digest content generated by the LLM.
        llm_name: Name of the LLM used.

    Returns:
        Complete markdown document.
    """
    header = create_digest_header(data, llm_name)
    return header + llm_digest


def get_default_output_filename(server_name: str) -> str:
    """Generate a default output filename.

    Args:
        server_name: Name of the Discord server.

    Returns:
        Filename with timestamp.
    """
    # Sanitize server name for filename
    safe_name = "".join(c if c.isalnum() or c in "._- " else "_" for c in server_name)
    safe_name = safe_name.replace(" ", "-").lower()
    timestamp = datetime.now().strftime("%Y%m%d-%H%M")
    return f"digest-{safe_name}-{timestamp}.md"
