"""Formatter utilities for digest generation."""

from datetime import datetime

from discord_chat.services.discord_client import ServerDigestData


class InvalidServerNameError(ValueError):
    """Raised when server name contains invalid characters."""

    pass


def validate_server_name(server_name: str) -> str:
    """Validate and sanitize server name to prevent path traversal attacks.

    Args:
        server_name: Raw server name from user input.

    Returns:
        Sanitized server name safe for filesystem operations.

    Raises:
        InvalidServerNameError: If server name is empty or contains path traversal attempts.
    """
    if not server_name or not server_name.strip():
        raise InvalidServerNameError("Server name cannot be empty")

    # Remove leading/trailing whitespace
    name = server_name.strip()

    # Block path traversal patterns
    if ".." in name or name.startswith("/") or name.startswith("\\"):
        raise InvalidServerNameError(
            f"Invalid server name '{server_name}': contains path traversal characters"
        )

    # Block null bytes and other dangerous characters
    if "\x00" in name or "\n" in name or "\r" in name:
        raise InvalidServerNameError(
            f"Invalid server name '{server_name}': contains control characters"
        )

    # Limit length to prevent filesystem issues
    if len(name) > 100:
        raise InvalidServerNameError(
            f"Server name too long ({len(name)} chars). Maximum is 100 characters."
        )

    return name


def format_messages_for_llm(data: ServerDigestData) -> str:
    """Format Discord messages into text for LLM consumption.

    Args:
        data: Server digest data containing all messages.

    Returns:
        Formatted text string with messages organized by channel.
    """
    if not data.channels:
        return "No messages found in the specified time period."

    lines = []
    for channel in data.channels:
        lines.append(f"## #{channel.channel_name}")
        lines.append("")

        for msg in channel.messages:
            timestamp = msg["timestamp"][:16].replace("T", " ")  # Trim to minute precision
            author = msg["author"]
            content = msg["content"]

            # Format the message
            lines.append(f"[{timestamp}] **{author}**: {content}")

            # Note attachments if any
            if msg["attachments"]:
                attachments = ", ".join(msg["attachments"])
                lines.append(f"  _Attachments: {attachments}_")

        lines.append("")

    return "\n".join(lines)


def format_time_range(start: datetime, end: datetime) -> str:
    """Format the time range for display.

    Args:
        start: Start datetime.
        end: End datetime.

    Returns:
        Human-readable time range string.
    """
    start_str = start.strftime("%Y-%m-%d %H:%M UTC")
    end_str = end.strftime("%Y-%m-%d %H:%M UTC")
    return f"{start_str} to {end_str}"


def create_digest_header(data: ServerDigestData, llm_name: str) -> str:
    """Create the header section for the digest output.

    Args:
        data: Server digest data.
        llm_name: Name of the LLM used for generation.

    Returns:
        Markdown header string.
    """
    time_range = format_time_range(data.start_time, data.end_time)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""# Discord Digest: {data.server_name}

**Generated:** {generated_at}
**Time Period:** {time_range}
**Channels with activity:** {len(data.channels)}
**Total messages:** {data.total_messages}
**Generated by:** {llm_name}

---

"""


def create_full_digest(
    data: ServerDigestData,
    llm_digest: str,
    llm_name: str,
) -> str:
    """Create the full digest document.

    Args:
        data: Server digest data.
        llm_digest: The digest content generated by the LLM.
        llm_name: Name of the LLM used.

    Returns:
        Complete markdown document.
    """
    header = create_digest_header(data, llm_name)
    return header + llm_digest


def get_default_output_filename(server_name: str) -> str:
    """Generate a default output filename.

    Args:
        server_name: Name of the Discord server.

    Returns:
        Filename with timestamp.

    Raises:
        InvalidServerNameError: If server name is invalid or would result in unsafe filename.
    """
    # Validate first to block path traversal attempts
    validated_name = validate_server_name(server_name)

    # Sanitize server name for filename - only allow alphanumeric, hyphen, underscore
    # Explicitly exclude dots to prevent hidden files or extension manipulation
    safe_name = "".join(c if c.isalnum() or c in "_- " else "_" for c in validated_name)
    safe_name = safe_name.replace(" ", "-").lower()

    # Remove any leading/trailing underscores or hyphens
    safe_name = safe_name.strip("-_")

    # Ensure we have something left
    if not safe_name:
        safe_name = "unknown-server"

    timestamp = datetime.now().strftime("%Y%m%d-%H%M")
    filename = f"digest-{safe_name}-{timestamp}.md"

    # Final safety check - ensure no path separators snuck through
    if "/" in filename or "\\" in filename:
        raise InvalidServerNameError("Generated filename contains path separators")

    return filename
